project_name: kubeswap
before:
  hooks:
    - go mod tidy
    - rm -rf dist
    - gofumpt -l -w .
builds:
  - binary: kubeswap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "7"
    ldflags:
      - -s -w -X=github.com/ebarped/kubeswap/cmd.Version={{.Version}} # go tool link flags
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: "386"
archives:
  - format_overrides:
    - goos: windows
      format: zip
release:
snapshot:
  name_template: "{{ .Tag }}-next"

